//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


//byla próba stworzenia formularza rejestracji ale siê nie uda³o sie dokonczyc
namespace Silownia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterC
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
